import { DEFAULT_SETTINGS } from "../../data/db.js";

export const state = {
  settingsCache: { ...DEFAULT_SETTINGS },
  pendingSettingsSave: null,
  tasksTimeMapsCache: [],
  tasksCache: [],
  taskTemplatesCache: [],
  taskFormMode: null,
  taskAiList: [],
  zoomFilter: null,
  collapsedSections: new Set(),
  collapsedSubsections: new Set(),
  collapsedTasks: new Set(),
  expandedTaskDetails: new Set(),
  taskDetailCleanup: new Map(),
  taskMenuCleanup: null,
  taskMenuOpenId: "",
  draggingTaskId: null,
  notificationHideTimeout: null,
  notificationUndoHandler: null,
  taskTitleEditCleanup: null,
  settingsCleanup: null,
  pageCleanup: null,
  navStack: [],
  navIndex: -1,
  sortableInstances: [],
  taskDeleteShortcutCleanup: null,
  tasksCalendarSplit: true,
  calendarViewMode: "day",
  calendarAnchorDate: new Date(),
  calendarExternalEvents: [],
  googleCalendarListCache: [],
  calendarExternalRange: null,
  calendarExternalRangeKey: "",
  calendarExternalPendingKey: "",
  calendarExternalAllowFetch: false,
  bulkEditActive: false,
  bulkEditCleanup: null,
  bulkEditSelectionIds: []
};
